# ============================================
# Google Cloud Build Configuration
# Builds and deploys to Cloud Run
# ============================================

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mega-management:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mega-management:latest'
      - '.'
    timeout: '1200s'  # 20 minutes for build (Sharp takes time)

  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mega-management:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mega-management:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mega-management'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mega-management:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'  # Mumbai region (closest to India)
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/mega-management:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/mega-management:latest'

# Build timeout (30 minutes total)
timeout: '1800s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Faster builds
